[2025-05-28T08:27:45.286+0000] {processor.py:161} INFO - Started process (PID=168) to work on /opt/airflow/dags/etl_dag.py
[2025-05-28T08:27:45.289+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-05-28T08:27:45.291+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:27:45.290+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:27:45.319+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:27:45.318+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 23
    task_id='run_
            ^
SyntaxError: unterminated string literal (detected at line 23)
[2025-05-28T08:27:45.320+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:27:45.351+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.071 seconds
[2025-05-28T08:40:42.398+0000] {processor.py:161} INFO - Started process (PID=168) to work on /opt/airflow/dags/etl_dag.py
[2025-05-28T08:40:42.415+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-05-28T08:40:42.472+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:40:42.463+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:40:42.580+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:40:42.556+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 23
    task_id='run_
            ^
SyntaxError: unterminated string literal (detected at line 23)
[2025-05-28T08:40:42.585+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:40:42.760+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.568 seconds
[2025-05-28T08:41:13.932+0000] {processor.py:161} INFO - Started process (PID=174) to work on /opt/airflow/dags/etl_dag.py
[2025-05-28T08:41:13.937+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-05-28T08:41:13.949+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:41:13.947+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:41:14.015+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:41:14.010+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 23
    task_id='run_
            ^
SyntaxError: unterminated string literal (detected at line 23)
[2025-05-28T08:41:14.016+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:41:14.149+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.247 seconds
[2025-05-28T08:41:44.630+0000] {processor.py:161} INFO - Started process (PID=179) to work on /opt/airflow/dags/etl_dag.py
[2025-05-28T08:41:44.648+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-05-28T08:41:44.724+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:41:44.715+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:41:44.841+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:41:44.817+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 23
    task_id='run_
            ^
SyntaxError: unterminated string literal (detected at line 23)
[2025-05-28T08:41:44.845+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:41:45.147+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.655 seconds
[2025-05-28T08:42:15.388+0000] {processor.py:161} INFO - Started process (PID=184) to work on /opt/airflow/dags/etl_dag.py
[2025-05-28T08:42:15.394+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-05-28T08:42:15.403+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:42:15.402+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:42:15.456+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:42:15.452+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 23
    task_id='run_
            ^
SyntaxError: unterminated string literal (detected at line 23)
[2025-05-28T08:42:15.458+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:42:15.512+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.149 seconds
[2025-05-28T08:42:46.432+0000] {processor.py:161} INFO - Started process (PID=189) to work on /opt/airflow/dags/etl_dag.py
[2025-05-28T08:42:46.435+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-05-28T08:42:46.441+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:42:46.440+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:42:46.491+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:42:46.489+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 23
    task_id='run_
            ^
SyntaxError: unterminated string literal (detected at line 23)
[2025-05-28T08:42:46.493+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:42:46.527+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.107 seconds
[2025-05-28T08:43:17.260+0000] {processor.py:161} INFO - Started process (PID=194) to work on /opt/airflow/dags/etl_dag.py
[2025-05-28T08:43:17.263+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-05-28T08:43:17.267+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:43:17.266+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:43:17.318+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:43:17.317+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 23
    task_id='run_
            ^
SyntaxError: unterminated string literal (detected at line 23)
[2025-05-28T08:43:17.319+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:43:17.351+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.097 seconds
[2025-05-28T08:43:48.079+0000] {processor.py:161} INFO - Started process (PID=199) to work on /opt/airflow/dags/etl_dag.py
[2025-05-28T08:43:48.083+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-05-28T08:43:48.094+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:43:48.094+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:43:48.147+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:43:48.146+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 23
    task_id='run_
            ^
SyntaxError: unterminated string literal (detected at line 23)
[2025-05-28T08:43:48.148+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:43:48.176+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.113 seconds
[2025-05-28T08:44:18.729+0000] {processor.py:161} INFO - Started process (PID=204) to work on /opt/airflow/dags/etl_dag.py
[2025-05-28T08:44:18.732+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-05-28T08:44:18.735+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:44:18.735+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:44:18.781+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:44:18.779+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 23
    task_id='run_
            ^
SyntaxError: unterminated string literal (detected at line 23)
[2025-05-28T08:44:18.784+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:44:18.811+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.088 seconds
[2025-05-28T08:44:49.406+0000] {processor.py:161} INFO - Started process (PID=209) to work on /opt/airflow/dags/etl_dag.py
[2025-05-28T08:44:49.409+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-05-28T08:44:49.415+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:44:49.414+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:44:49.469+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:44:49.464+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 23
    task_id='run_
            ^
SyntaxError: unterminated string literal (detected at line 23)
[2025-05-28T08:44:49.472+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:44:49.595+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.201 seconds
[2025-05-28T08:45:20.086+0000] {processor.py:161} INFO - Started process (PID=214) to work on /opt/airflow/dags/etl_dag.py
[2025-05-28T08:45:20.089+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-05-28T08:45:20.092+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:45:20.091+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:45:20.145+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:45:20.142+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 23
    task_id='run_
            ^
SyntaxError: unterminated string literal (detected at line 23)
[2025-05-28T08:45:20.147+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:45:20.173+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.095 seconds
[2025-05-28T08:45:50.545+0000] {processor.py:161} INFO - Started process (PID=224) to work on /opt/airflow/dags/etl_dag.py
[2025-05-28T08:45:50.547+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-05-28T08:45:50.550+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:45:50.549+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:45:50.624+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:45:50.619+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 23
    task_id='run_
            ^
SyntaxError: unterminated string literal (detected at line 23)
[2025-05-28T08:45:50.631+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:45:50.688+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.149 seconds
[2025-05-28T08:46:21.493+0000] {processor.py:161} INFO - Started process (PID=234) to work on /opt/airflow/dags/etl_dag.py
[2025-05-28T08:46:21.494+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-05-28T08:46:21.497+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:46:21.497+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:46:21.553+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:46:21.551+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 23
    task_id='run_
            ^
SyntaxError: unterminated string literal (detected at line 23)
[2025-05-28T08:46:21.554+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:46:21.583+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.096 seconds
[2025-05-28T08:46:52.211+0000] {processor.py:161} INFO - Started process (PID=244) to work on /opt/airflow/dags/etl_dag.py
[2025-05-28T08:46:52.214+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-05-28T08:46:52.223+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:46:52.222+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:46:52.262+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:46:52.261+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 23
    task_id='run_
            ^
SyntaxError: unterminated string literal (detected at line 23)
[2025-05-28T08:46:52.263+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:46:52.283+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.087 seconds
[2025-05-28T08:47:22.840+0000] {processor.py:161} INFO - Started process (PID=254) to work on /opt/airflow/dags/etl_dag.py
[2025-05-28T08:47:22.842+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-05-28T08:47:22.845+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:47:22.845+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:47:22.918+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:47:22.915+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 23
    task_id='run_
            ^
SyntaxError: unterminated string literal (detected at line 23)
[2025-05-28T08:47:22.920+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:47:22.998+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.165 seconds
[2025-05-28T08:47:53.599+0000] {processor.py:161} INFO - Started process (PID=264) to work on /opt/airflow/dags/etl_dag.py
[2025-05-28T08:47:53.602+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-05-28T08:47:53.613+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:47:53.611+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:47:53.663+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:47:53.662+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 23
    task_id='run_
            ^
SyntaxError: unterminated string literal (detected at line 23)
[2025-05-28T08:47:53.665+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:47:53.710+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.120 seconds
[2025-05-28T08:48:24.286+0000] {processor.py:161} INFO - Started process (PID=274) to work on /opt/airflow/dags/etl_dag.py
[2025-05-28T08:48:24.290+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-05-28T08:48:24.292+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:48:24.292+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:48:24.344+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:48:24.343+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 23
    task_id='run_
            ^
SyntaxError: unterminated string literal (detected at line 23)
[2025-05-28T08:48:24.345+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:48:24.379+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.098 seconds
[2025-05-28T08:49:43.787+0000] {processor.py:161} INFO - Started process (PID=171) to work on /opt/airflow/dags/etl_dag.py
[2025-05-28T08:49:43.800+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-05-28T08:49:43.841+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:49:43.838+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:49:43.909+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:49:43.891+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 23
    task_id='run_
            ^
SyntaxError: unterminated string literal (detected at line 23)
[2025-05-28T08:49:43.911+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:49:44.070+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.386 seconds
[2025-05-28T08:50:14.710+0000] {processor.py:161} INFO - Started process (PID=181) to work on /opt/airflow/dags/etl_dag.py
[2025-05-28T08:50:14.713+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-05-28T08:50:14.729+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:50:14.727+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:50:14.799+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:50:14.790+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 23
    task_id='run_
            ^
SyntaxError: unterminated string literal (detected at line 23)
[2025-05-28T08:50:14.800+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:50:14.922+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.268 seconds
[2025-05-28T08:50:45.433+0000] {processor.py:161} INFO - Started process (PID=191) to work on /opt/airflow/dags/etl_dag.py
[2025-05-28T08:50:45.435+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-05-28T08:50:45.439+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:50:45.438+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:50:45.489+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:50:45.487+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 23
    task_id='run_
            ^
SyntaxError: unterminated string literal (detected at line 23)
[2025-05-28T08:50:45.490+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:50:45.532+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.107 seconds
[2025-05-28T08:51:16.167+0000] {processor.py:161} INFO - Started process (PID=201) to work on /opt/airflow/dags/etl_dag.py
[2025-05-28T08:51:16.172+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-05-28T08:51:16.186+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:51:16.183+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:51:16.266+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:51:16.252+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 23
    task_id='run_
            ^
SyntaxError: unterminated string literal (detected at line 23)
[2025-05-28T08:51:16.269+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:51:16.449+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.332 seconds
[2025-05-28T08:51:46.675+0000] {processor.py:161} INFO - Started process (PID=211) to work on /opt/airflow/dags/etl_dag.py
[2025-05-28T08:51:46.676+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-05-28T08:51:46.680+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:51:46.679+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:51:46.717+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:51:46.716+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 23
    task_id='run_
            ^
SyntaxError: unterminated string literal (detected at line 23)
[2025-05-28T08:51:46.719+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:51:46.769+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.101 seconds
[2025-05-28T08:52:17.224+0000] {processor.py:161} INFO - Started process (PID=221) to work on /opt/airflow/dags/etl_dag.py
[2025-05-28T08:52:17.230+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-05-28T08:52:17.236+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:52:17.236+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:52:17.290+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:52:17.289+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 23
    task_id='run_
            ^
SyntaxError: unterminated string literal (detected at line 23)
[2025-05-28T08:52:17.291+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:52:17.349+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.133 seconds
[2025-05-28T08:52:47.722+0000] {processor.py:161} INFO - Started process (PID=231) to work on /opt/airflow/dags/etl_dag.py
[2025-05-28T08:52:47.725+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-05-28T08:52:47.728+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:52:47.728+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:52:47.772+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:52:47.771+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 23
    task_id='run_
            ^
SyntaxError: unterminated string literal (detected at line 23)
[2025-05-28T08:52:47.773+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:52:47.807+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.091 seconds
[2025-05-28T08:53:18.263+0000] {processor.py:161} INFO - Started process (PID=241) to work on /opt/airflow/dags/etl_dag.py
[2025-05-28T08:53:18.265+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-05-28T08:53:18.269+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:53:18.268+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:53:18.319+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:53:18.318+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 23
    task_id='run_
            ^
SyntaxError: unterminated string literal (detected at line 23)
[2025-05-28T08:53:18.321+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:53:18.356+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.099 seconds
[2025-05-28T08:53:48.731+0000] {processor.py:161} INFO - Started process (PID=251) to work on /opt/airflow/dags/etl_dag.py
[2025-05-28T08:53:48.733+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-05-28T08:53:48.735+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:53:48.735+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:53:48.775+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:53:48.774+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 23
    task_id='run_
            ^
SyntaxError: unterminated string literal (detected at line 23)
[2025-05-28T08:53:48.777+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:53:48.823+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.097 seconds
[2025-05-28T08:54:19.290+0000] {processor.py:161} INFO - Started process (PID=261) to work on /opt/airflow/dags/etl_dag.py
[2025-05-28T08:54:19.292+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-05-28T08:54:19.296+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:54:19.295+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:54:19.348+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:54:19.347+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 23
    task_id='run_
            ^
SyntaxError: unterminated string literal (detected at line 23)
[2025-05-28T08:54:19.349+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:54:19.398+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.117 seconds
[2025-05-28T08:54:49.970+0000] {processor.py:161} INFO - Started process (PID=271) to work on /opt/airflow/dags/etl_dag.py
[2025-05-28T08:54:49.972+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-05-28T08:54:49.975+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:54:49.974+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:54:50.022+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:54:50.020+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 23
    task_id='run_
            ^
SyntaxError: unterminated string literal (detected at line 23)
[2025-05-28T08:54:50.024+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:54:50.057+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.091 seconds
[2025-05-28T08:55:20.472+0000] {processor.py:161} INFO - Started process (PID=281) to work on /opt/airflow/dags/etl_dag.py
[2025-05-28T08:55:20.475+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-05-28T08:55:20.477+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:55:20.476+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:55:20.514+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:55:20.511+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 23
    task_id='run_
            ^
SyntaxError: unterminated string literal (detected at line 23)
[2025-05-28T08:55:20.516+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:55:20.564+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.102 seconds
[2025-05-28T08:55:51.107+0000] {processor.py:161} INFO - Started process (PID=291) to work on /opt/airflow/dags/etl_dag.py
[2025-05-28T08:55:51.109+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-05-28T08:55:51.111+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:55:51.111+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:55:51.159+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:55:51.158+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 23
    task_id='run_
            ^
SyntaxError: unterminated string literal (detected at line 23)
[2025-05-28T08:55:51.161+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:55:51.191+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.089 seconds
[2025-05-28T08:56:21.716+0000] {processor.py:161} INFO - Started process (PID=301) to work on /opt/airflow/dags/etl_dag.py
[2025-05-28T08:56:21.718+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2025-05-28T08:56:21.721+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:56:21.720+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:56:21.771+0000] {logging_mixin.py:188} INFO - [2025-05-28T08:56:21.770+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 23
    task_id='run_
            ^
SyntaxError: unterminated string literal (detected at line 23)
[2025-05-28T08:56:21.772+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2025-05-28T08:56:21.795+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.083 seconds
