[2025-06-16T10:12:45.501+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-16T10:12:45.628+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_brazil_pipeline.run_dbt_models manual__2025-06-16T10:07:39.958242+00:00 [queued]>
[2025-06-16T10:12:45.651+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_brazil_pipeline.run_dbt_models manual__2025-06-16T10:07:39.958242+00:00 [queued]>
[2025-06-16T10:12:45.653+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-06-16T10:12:45.689+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_dbt_models> on 2025-06-16 10:07:39.958242+00:00
[2025-06-16T10:12:45.713+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_brazil_pipeline', 'run_dbt_models', 'manual__2025-06-16T10:07:39.958242+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/etl_brazil_pipeline.py', '--cfg-path', '/tmp/tmp0qb0b7zi']
[2025-06-16T10:12:45.727+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=333) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-16T10:12:45.731+0000] {standard_task_runner.py:91} INFO - Job 15: Subtask run_dbt_models
[2025-06-16T10:12:45.731+0000] {standard_task_runner.py:63} INFO - Started process 334 to run task
[2025-06-16T10:12:45.816+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-16T10:12:45.949+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_brazil_pipeline.run_dbt_models manual__2025-06-16T10:07:39.958242+00:00 [running]> on host 155077edd2ca
[2025-06-16T10:12:46.198+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='vaishnavi' AIRFLOW_CTX_DAG_ID='etl_brazil_pipeline' AIRFLOW_CTX_TASK_ID='run_dbt_models' AIRFLOW_CTX_EXECUTION_DATE='2025-06-16T10:07:39.958242+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-16T10:07:39.958242+00:00'
[2025-06-16T10:12:46.201+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-16T10:12:46.273+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-16T10:12:46.279+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/airflow/dbt_project && dbt run']
[2025-06-16T10:12:46.305+0000] {subprocess.py:86} INFO - Output:
[2025-06-16T10:12:46.346+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: dbt: command not found
[2025-06-16T10:12:46.348+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-06-16T10:12:46.352+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-16T10:12:46.377+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-06-16T10:12:46.393+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_brazil_pipeline, task_id=run_dbt_models, run_id=manual__2025-06-16T10:07:39.958242+00:00, execution_date=20250616T100739, start_date=20250616T101245, end_date=20250616T101246
[2025-06-16T10:12:46.425+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 15 for task run_dbt_models (Bash command failed. The command returned a non-zero exit code 127.; 334)
[2025-06-16T10:12:46.454+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-16T10:12:46.499+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-16T10:12:46.508+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
