[2025-06-11T10:55:10.367+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-11T10:55:10.658+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_brazil_pipeline.run_etl_script manual__2025-06-11T10:55:05.272081+00:00 [queued]>
[2025-06-11T10:55:10.701+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_brazil_pipeline.run_etl_script manual__2025-06-11T10:55:05.272081+00:00 [queued]>
[2025-06-11T10:55:10.703+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-11T10:55:10.742+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_etl_script> on 2025-06-11 10:55:05.272081+00:00
[2025-06-11T10:55:10.764+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_brazil_pipeline', 'run_etl_script', 'manual__2025-06-11T10:55:05.272081+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/etl_brazil_pipeline.py', '--cfg-path', '/tmp/tmpo8b8ny75']
[2025-06-11T10:55:10.785+0000] {standard_task_runner.py:91} INFO - Job 2: Subtask run_etl_script
[2025-06-11T10:55:10.784+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=545) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-11T10:55:10.787+0000] {standard_task_runner.py:63} INFO - Started process 546 to run task
[2025-06-11T10:55:10.871+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-11T10:55:11.017+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_brazil_pipeline.run_etl_script manual__2025-06-11T10:55:05.272081+00:00 [running]> on host 5698a207bf0f
[2025-06-11T10:55:11.295+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='vaishnavi' AIRFLOW_CTX_DAG_ID='etl_brazil_pipeline' AIRFLOW_CTX_TASK_ID='run_etl_script' AIRFLOW_CTX_EXECUTION_DATE='2025-06-11T10:55:05.272081+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-11T10:55:05.272081+00:00'
[2025-06-11T10:55:11.298+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-11T10:55:11.419+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-11T10:55:11.424+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/airflow/src/etl/brazil_etl.py']
[2025-06-11T10:55:11.459+0000] {subprocess.py:86} INFO - Output:
[2025-06-11T10:55:17.708+0000] {subprocess.py:93} INFO - 📥 Reading data/raw/olist_customers_dataset.csv
[2025-06-11T10:55:17.710+0000] {subprocess.py:93} INFO - ❌ ERROR while processing data/raw/olist_customers_dataset.csv -> [Errno 2] No such file or directory: 'data/raw/olist_customers_dataset.csv'
[2025-06-11T10:55:17.711+0000] {subprocess.py:93} INFO - 
[2025-06-11T10:55:17.712+0000] {subprocess.py:93} INFO - 📥 Reading data/raw/olist_geolocation_dataset.csv
[2025-06-11T10:55:17.714+0000] {subprocess.py:93} INFO - ❌ ERROR while processing data/raw/olist_geolocation_dataset.csv -> [Errno 2] No such file or directory: 'data/raw/olist_geolocation_dataset.csv'
[2025-06-11T10:55:17.715+0000] {subprocess.py:93} INFO - 
[2025-06-11T10:55:17.717+0000] {subprocess.py:93} INFO - 📥 Reading data/raw/olist_orders_dataset.csv
[2025-06-11T10:55:17.718+0000] {subprocess.py:93} INFO - ❌ ERROR while processing data/raw/olist_orders_dataset.csv -> [Errno 2] No such file or directory: 'data/raw/olist_orders_dataset.csv'
[2025-06-11T10:55:17.720+0000] {subprocess.py:93} INFO - 
[2025-06-11T10:55:17.722+0000] {subprocess.py:93} INFO - 📥 Reading data/raw/olist_order_items_dataset.csv
[2025-06-11T10:55:17.723+0000] {subprocess.py:93} INFO - ❌ ERROR while processing data/raw/olist_order_items_dataset.csv -> [Errno 2] No such file or directory: 'data/raw/olist_order_items_dataset.csv'
[2025-06-11T10:55:17.725+0000] {subprocess.py:93} INFO - 
[2025-06-11T10:55:17.726+0000] {subprocess.py:93} INFO - 📥 Reading data/raw/olist_order_payments_dataset.csv
[2025-06-11T10:55:17.727+0000] {subprocess.py:93} INFO - ❌ ERROR while processing data/raw/olist_order_payments_dataset.csv -> [Errno 2] No such file or directory: 'data/raw/olist_order_payments_dataset.csv'
[2025-06-11T10:55:17.728+0000] {subprocess.py:93} INFO - 
[2025-06-11T10:55:17.730+0000] {subprocess.py:93} INFO - 📥 Reading data/raw/olist_order_reviews_dataset.csv
[2025-06-11T10:55:17.731+0000] {subprocess.py:93} INFO - ❌ ERROR while processing data/raw/olist_order_reviews_dataset.csv -> [Errno 2] No such file or directory: 'data/raw/olist_order_reviews_dataset.csv'
[2025-06-11T10:55:17.733+0000] {subprocess.py:93} INFO - 
[2025-06-11T10:55:17.734+0000] {subprocess.py:93} INFO - 📥 Reading data/raw/olist_products_dataset.csv
[2025-06-11T10:55:17.735+0000] {subprocess.py:93} INFO - ❌ ERROR while processing data/raw/olist_products_dataset.csv -> [Errno 2] No such file or directory: 'data/raw/olist_products_dataset.csv'
[2025-06-11T10:55:17.736+0000] {subprocess.py:93} INFO - 
[2025-06-11T10:55:17.737+0000] {subprocess.py:93} INFO - 📥 Reading data/raw/olist_sellers_dataset.csv
[2025-06-11T10:55:17.738+0000] {subprocess.py:93} INFO - ❌ ERROR while processing data/raw/olist_sellers_dataset.csv -> [Errno 2] No such file or directory: 'data/raw/olist_sellers_dataset.csv'
[2025-06-11T10:55:17.739+0000] {subprocess.py:93} INFO - 
[2025-06-11T10:55:17.740+0000] {subprocess.py:93} INFO - 📥 Reading data/raw/product_category_name_translation.csv
[2025-06-11T10:55:17.741+0000] {subprocess.py:93} INFO - ❌ ERROR while processing data/raw/product_category_name_translation.csv -> [Errno 2] No such file or directory: 'data/raw/product_category_name_translation.csv'
[2025-06-11T10:55:17.742+0000] {subprocess.py:93} INFO - 
[2025-06-11T10:55:17.898+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-06-11T10:55:17.904+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-11T10:55:17.965+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_brazil_pipeline, task_id=run_etl_script, run_id=manual__2025-06-11T10:55:05.272081+00:00, execution_date=20250611T105505, start_date=20250611T105510, end_date=20250611T105517
[2025-06-11T10:55:18.021+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-06-11T10:55:18.045+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-11T10:55:18.048+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
