[2025-06-16T12:58:23.360+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-16T12:58:23.429+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_brazil_pipeline.run_dbt_models manual__2025-06-16T12:47:50.853434+00:00 [queued]>
[2025-06-16T12:58:23.450+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_brazil_pipeline.run_dbt_models manual__2025-06-16T12:47:50.853434+00:00 [queued]>
[2025-06-16T12:58:23.451+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-16T12:58:23.479+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_dbt_models> on 2025-06-16 12:47:50.853434+00:00
[2025-06-16T12:58:23.527+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=633) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-16T12:58:23.533+0000] {standard_task_runner.py:63} INFO - Started process 661 to run task
[2025-06-16T12:58:23.532+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_brazil_pipeline', 'run_dbt_models', 'manual__2025-06-16T12:47:50.853434+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/etl_brazil_pipeline.py', '--cfg-path', '/tmp/tmp9xav2l4y']
[2025-06-16T12:58:23.537+0000] {standard_task_runner.py:91} INFO - Job 46: Subtask run_dbt_models
[2025-06-16T12:58:23.568+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-06-16T12:58:23.647+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_brazil_pipeline.run_dbt_models manual__2025-06-16T12:47:50.853434+00:00 [running]> on host 1055b69d82fc
[2025-06-16T12:58:23.832+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='vaishnavi' AIRFLOW_CTX_DAG_ID='etl_brazil_pipeline' AIRFLOW_CTX_TASK_ID='run_dbt_models' AIRFLOW_CTX_EXECUTION_DATE='2025-06-16T12:47:50.853434+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-16T12:47:50.853434+00:00'
[2025-06-16T12:58:23.834+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-16T12:58:23.871+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-16T12:58:23.875+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/airflow/dbt_project && /home/airflow/.local/bin/dbt run']
[2025-06-16T12:58:23.908+0000] {subprocess.py:86} INFO - Output:
[2025-06-16T12:58:30.384+0000] {subprocess.py:93} INFO - Usage: dbt run [OPTIONS]
[2025-06-16T12:58:30.386+0000] {subprocess.py:93} INFO - Try 'dbt run -h' for help.
[2025-06-16T12:58:30.388+0000] {subprocess.py:93} INFO - 
[2025-06-16T12:58:30.390+0000] {subprocess.py:93} INFO - Error: Invalid value for '--profiles-dir': Path '/home/airflow/.dbt' does not exist.
[2025-06-16T12:58:30.892+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-06-16T12:58:30.895+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-16T12:58:30.920+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-06-16T12:58:30.937+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_brazil_pipeline, task_id=run_dbt_models, run_id=manual__2025-06-16T12:47:50.853434+00:00, execution_date=20250616T124750, start_date=20250616T125823, end_date=20250616T125830
[2025-06-16T12:58:30.972+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 46 for task run_dbt_models (Bash command failed. The command returned a non-zero exit code 2.; 661)
[2025-06-16T12:58:31.016+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-16T12:58:31.080+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-16T12:58:31.087+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
